name: Trigger action on CRON
on:
 schedule:
  - cron: '*/2 * * * *'
jobs:
 test-schedule:
  runs-on: ubuntu-latest
   steps:
    - name: run every halfan hour
      run: echo "Running every 30 minutes"
